PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX pk: <http://opensensingcity.emse.fr/ontologies/parking/>
PREFIX pkr: <http://opensensingcity.emse.fr/Parking/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?name ?lat ?long
WHERE {
        _:x rdfs:label ?name;
                       geo:lat ?lat;
                       geo:long ?long;
}