PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX pk: <http://opensensingcity.emse.fr/ontologies/parking/>
PREFIX pkr: <http://opensensingcity.emse.fr/Parking/resource/>
SELECT ?name ?lat ?long
WHERE {
        pkr:Parking570 rdfs:label ?name;
                       geo:lat ?lat;
                       geo:long ?long;
}